#!/usr/bin/env bash
#kills the infinity and beyond  program using sigkill signal
#get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)
#terminate the infinite process
if [ -n "$id" ]
then
 kill -15 "$id"
fi

