#!/usr/bin/env bash
#display infinity and beyond indefinitely with a sleep 2 betweeneach iteration
trap "echo 'I am invincible!!!'" SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done

