#!/usr/bin/env bash
# Kill the script that displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration
# and displays "I am invincible!!!" when receiving a SIGTERM signal
read -p "Enter the PID of the script to kill: " PID

kill -9 "$PID"
