#!/usr/bin/env bash
# Kill the script that displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration
# and displays "I am invincible!!!" when receiving a SIGTERM signal
kill -9 "$(pgrep -f highlander)"

