#!/urs/bin/env bash
#6-superstitious_numbers
count=1

while [ $count -le 20 ]
do
  case $count in
    4)
      echo "4"
      echo "Bad luck from China"
      ;;
    9)
      echo "9"
      echo "Bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "Bad luck from Italy"
      ;;
    *)
      echo "$count"
      ;;
  esac
  count=$((count + 1))
done

