#!/usr/bin/env bash
#display hours from 0 to 12
hours=0
minutes=0

while [ $hours -lt 13 ]
do
  while [ $minutes -lt 60 ]
  do
    echo "$hours:$minutes"
    minutes=$((minutes + 1))
  done
  hours=$((hours + 1))
  minutes=0
done | head -70
